### ISSUE TITLE
I18n for error message attributes merged from ActiveRecord

### ISSUE THREAD

**Issue by ivdma** [orgsync/active_interaction#374]
Hi guys, 

I am fighting with translating error messages that come out of ActiveRecord merged by ActiveInteraction. I can't get attribute names correctly translated. 

Assume I have following classes:

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
end

# app/interactions/create_user.rb
class CreateUser < ActiveInteraction::Base
  def execute
    user = User.first         # Assume I have any users.
    user.update email: nil    # ActiveRecord will mark user invalid with errors.
    errors.merge!(user.errors) if user.errors.any?
    user
  end
end
```

and these translations:

```yaml
# config/locales/models/user.nl.yml
nl:
  activerecord:
    attributes:
      user:
        email: E-mailadres # which I want to be used instead of some `attribute.humanize` magic.
  errors:
    messages:
      blank: moet opgegeven zijn
```

So when I `CreateUser.run` the interaction, it returns the following `errors.full_messages`:

```ruby
["Email moet opgegeven zijn"] # Should be `["E-mailadres moet opgegeven zijn"]`
```

Which makes sense to developers, but not to endusers. 

Question is: Is there a way to also translate those attributes?

**Comment by AaronLasseigne** [comment]
They're translated as `types` within `ActiveInteraction`. Take a look at https://github.com/orgsync/active_interaction/blob/master/lib/active_interaction/locale/ folder for examples.

Let me know if this helps out.

**Comment by ivdma** [comment]
So basically I can do the following?

```yaml
nl:
  active_interaction:
    types:
      email: E-mailadres
```

Does it also mean there's is no way to translate column names which, as a result of bad software design, have the same names, but a slightly different meaning across the tables/objects? For example `Person#address` would translate to 'Home address' and `User#address` to 'Work address'.

**Comment by AaronLasseigne** [comment]
You should be able to do:

```yml
en:
  active_interaction:
    attributes:
      person:
        address: Home address
      user:
        address: Work address
```

**Comment by ivdma** [comment]
Hey @AaronLasseigne, 

Unfortunately, after lot's of debugging, I figured out that ActiveInteraction doesn't really respect ActiveRecord when merging errors. The following worked for me:

```yaml
nl:
  active_interaction:
    attributes:
      create_user:
        email: E-mailadres
```

Notice `create_user` which is a snake case version of my interaction's name `CreateUser`. This is either:
a) undocumented; or
b) a bug in [ActiveInteraction::Errors#attribute?](https://github.com/orgsync/active_interaction/blob/master/lib/active_interaction/errors.rb#L131) method which assumes `ActiveModel::Errors`'s  `@base` instance, which is at that point `CreateUser < ActiveInteraction::Base` and **not** `User < ActiveRecord::Base`.
